# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "doink_left", "doink_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
# ---
include:
  - board: nice_nano_v2
    shield: pskeeb5_left
  - board: nice_nano_v2
    shield: pskeeb5_right
    # snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: settings_reset
# include:
#   - board: nice_nano_v2
#     shield: doink_left
#   - board: nice_nano_v2
#     shield: doink_right
#   - board: nice_nano_v2
#     shield: settings_reset
